name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    env:
      DATABASE_URL: postgres://root:password@localhost:5432/aurora
      SESSION_SECRET: impossibletoguess

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: aurora
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile
        working-directory: .

      - run: pnpm prisma generate
      - run: pnpm db:migrate
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build

  docs:
    name: Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/docs

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile
        working-directory: .

      - run: pnpm build
